2021-03-30 21:35:52,577 ERROR: Exception on /auth/resetpass [POST] [in /home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/sora8d/Documents/Code/FAIF/application/auth/routes.py", line 44, in resetpasscheck
    send_reset_email(user)
  File "/home/sora8d/Documents/Code/FAIF/application/auth/email.py", line 6, in send_reset_email
    sender=app.config['MAIL_USERNAME'],
NameError: name 'app' is not defined
2021-03-30 21:36:58,526 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:74]
2021-03-30 21:37:02,868 ERROR: Exception on /auth/resetpass [POST] [in /home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/sora8d/Documents/Code/FAIF/application/auth/routes.py", line 44, in resetpasscheck
    send_reset_email(user)
  File "/home/sora8d/Documents/Code/FAIF/application/auth/email.py", line 9, in send_reset_email
    text_body=render_template('email/reseet_password.txt', user=user, token=token),
NameError: name 'render_template' is not defined
2021-03-30 21:37:14,828 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:74]
2021-03-30 21:37:41,814 ERROR: Exception on /auth/resetpass [POST] [in /home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/sora8d/Documents/Code/FAIF/application/auth/routes.py", line 44, in resetpasscheck
    send_reset_email(user)
  File "/home/sora8d/Documents/Code/FAIF/application/auth/email.py", line 9, in send_reset_email
    text_body=render_template('email/reseet_password.txt', user=user, token=token),
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/sora8d/Documents/Code/FAIF/application/templates/email/reseet_password.txt", line 4, in top-level template code
    This is the link= {{ url_for('resetpass', token=token, _external=True) }}
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'resetpass' with values ['token']. Did you mean 'auth.resetpass' instead?
2021-03-30 21:40:28,889 ERROR: Exception on /auth/resetpass [POST] [in /home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/sora8d/Documents/Code/FAIF/application/auth/routes.py", line 44, in resetpasscheck
    send_reset_email(user)
  File "/home/sora8d/Documents/Code/FAIF/application/auth/email.py", line 9, in send_reset_email
    text_body=render_template('email/reseet_password.txt', user=user, token=token),
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/sora8d/Documents/Code/FAIF/application/templates/email/reseet_password.txt", line 4, in top-level template code
    This is the link= {{ url_for('auth.resetpass', token=token, _external=True) }}
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/home/sora8d/Documents/AllVENV/FAIF/lib/python3.9/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'resetpass' with values ['token']. Did you mean 'auth.resetpass' instead?
2021-03-30 21:40:33,228 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:74]
2021-03-30 21:48:48,445 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:74]
2021-03-30 21:54:51,644 INFO: Ya Server startup [in /home/sora8d/Documents/Code/FAIF/application/__init__.py:74]
